# Jupyter Notebook 사용방법


- 코드 입력 방법:  
코드 셀에 파이썬 코드를 넣고, [Run] 버튼을 누르면 코드가 실행되면서 결과가 코드 셀 하단에 출력된다. 이 때 ln [ ]:이 ln [1]:로 바뀌고, 다른 코드 셀을 실행할 때마다 [ ]안에 있는 번호가 증가한다.

In [4]:
1+2

3

- 코드 셀 추가, 삭제:  
새로운 코드 셀을 추가하기 위해서는 [+], 현재 선택된 코드 셀을 삭제하기 위해서는 가위표시 툴바를 누르면 된다.

- 메뉴의 [Markdown]을 선택하면 코드에 대한 설명을 작성할 수 있다. \# 은 제목이라는 뜻이며 \# 이 하나씩 늘어날수록 하위 제목이 된다.

In [ ]:
# Python start
## Ch1

- 제목 변경:  
노트북의 Jupyter 로고 옆의 Untitled를 클릭하면 노트북의 제목을 변경할 수 있다.

- 파일로 저장:
메뉴의 [File] > [Save and Checkpoint]를 클릭하면 노트북이 *.ipynb 파일로 저장된다. 

- 코드 셀에서 변수를 만들면 다른 코드 셀에서 해당 변수를 사용할 수 있다. 

- 코드 셀의 실행 순서는 ln [ ]: 에 표시된 숫자 순서를 따른다.

$\Longrightarrow$ 이처럼 주피터 노트북은 코드, 코드의 실행 결과, 코드에 대한 설명을 한 번에 작성할 수 있어서 체계적인 기록이 가능하다. 


# Python의 변수 생성

In [1]:
3+5

8

In [6]:
a=3+5
a+2

10

In [7]:
1a=3+5
1a+2

SyntaxError: invalid decimal literal (1554485228.py, line 1)

<hr>

# 파이썬 기초 문법
## 사칙연산


1 더하기(+) 2는 3이라는 값을 출력해 보자. 보통 계산기 사용하듯 더하기 기호만 넣어 주면 된다.

In [8]:
1+2

3

나눗셈(/)과 곱셈(*) 역시 예상한 대로 결괏값을 보여준다.

In [9]:
3/1.5

2.0

In [10]:
3*3

9

## 변수 사용하여 계산 하기

In [11]:
# 아래 예제는 변수 a 에 1을, b에 2를 대입한 다음 a와 b를 더하면 3이라는 결괏값을 보여 준다.
a=1
b=2
a+b

3

 하나의 명령어는 한 줄에 입력되는 것이 기본이지만 세미콜론(;)을 사용하여 한 줄에서 명령어를 나눌 수도 있다. 
 print() 함수를 사용하여 변수의 값을 출력 할 수 있다.

In [12]:
print(a);print(b)
print(a+b)

1
2
3


In [13]:
a;b

2

## 제어문 (Control Statement)
- if, while, for 등의 제어문에 대해서 배워본다. 
- 제어문을 통해서 프로그램의 구조를 살펴보자.

* Tips : 제어문을 다루기 전에 다음의 사항을 미리 확인해 보자!


    - 제어문에 속하는 모든 문장은 반드시 들여쓰기를 해 주어야 함(들여쓰기를 하지 않는 경우 오류 발생)
    - 제어문에 속하는 모든 문장들의 들여쓰기 너비가 동일해야 함(동일하지 않은 경우 오류 발생)
    - 들여쓰기는 TAB 한 번 또는 스페이스 4칸으로 사용하는데, 탭은 환경에 따라 공백 수가 다를 수 있어서 스페이스로 사용하는 추세

### 조건문 if



* if 조건문은 조건을 판별할 때 사용하는 문장을 말한다. 
* 조건의 참, 거짓 여부에 따라 프로그램 제어 또는 반복하는 수행을 할 수 있다. 

#### if 문의 기본 구조

if 조건문:

    수행할 문장1
    수행할 문장2
    ...
elif 조건문:

    수행할 문장1
    수행할 문장2
    ...
else:
    
    수행할 문장1
    수행할 문장2
    ...

다음은 간단한 조건문 if를 사용한 예제이다. a가 1보다 크면 "a is greater than 1"이라는 문장을출력 (print)하라는 뜻이다.

In [14]:
a=2

if a>1:
    print("a is greater than 1")

a is greater than 1


#### 비교 연산자
* 조건문에서 조건의 만족 여부를 판단하기 위해 사용되는 비교연산자를 사용하는 방법을 알아보자.

|비교 연산자|설명|
|:-------:|:---:|
|x < y|	x가 y보다 작다|
|x > y|	x가 y보다 크다|
|x == y|	x와 y가 같다|
|x != y	|x와 y가 같지 않다|
|x >= y|	x가 y보다 크거나 같다|
|x <= y	|x가 y보다 작거나 같다|

In [16]:
x = 200
y = 100
x > y # 해당 조건은 True

True

아래와 같이 if elif else 를 이용한 조건문을 확인해 보자.

In [17]:
# 표현 1
if x > y:
    print('x가 y보다 크다.')
elif x<y:
    print('x가 y보다 작다.')
else:
    print('x가 y가 같다.')

x가 y보다 크다.


이번엔 if else 문을 확인해 보자.

In [18]:
# if else 문 : 표현1
score=75

if score>=60: 
    message = "success"
else: 
    message = "failure"
print(message)

success


#### and, or, not 사용
* 조건을 판단하기 위해 사용하는 다른 연산자로는 and, or, not이 있다. 각각의 연산자는 다음처럼 동작한다.

|연산자	|설명|
|:--------: | :--:|
|x or y|	x와 y 둘중에 하나만 참이어도 참이다.|
|x and y|	x와 y 모두 참이어야 참이다.|
|not x |x가 거짓이면 참이다.|

In [19]:
money = 2000
card = True

if money >= 3000 or card:
    print("지금 사자!")
else:
    print("나중에 사자")

지금 사자!


### 반복문 for

* while문과 비슷한 반복문인 for문은 매우 유용하고 문장 구조가 한눈에 쏙 들어온다는 장점이 있다.

for 문의 기본 구조는 아래와 같다. 

for 변수 in 리스트(또는 튜플, 문자열):
    
    수행할 문장1
    수행할 문장2
    ...

리스트나 튜플, 문자열의 첫 번째 요소부터 마지막 요소까지 차례로 변수에 대입되어 "수행할 문장1", "수행할 문장2" 등이 수행된다.

다양한 for 문의 예시를 확인해보자.

- 다음은 반복문 for를 사용해서 [1, 2, 3] 안의 값을 하나씩 출력하는 것을 보여 주는 예이다.  
- for문을 사용하면 실행해야 할 문장을 여러 번 반복해서 실행시킬 수 있다.<br>
- 아래 예는 대괄호 ([ ])사이에 있는 값들을 하나씩 출력한다.  
  - 아래 코드의 의미는 "[1, 2, 3] 리스트의 앞에서부터 하나씩 꺼내어 a 변수에 대입한 후 print(a)를 수행하라"이다.  
  - 당연히 a에 차례로 1, 2, 3이라는 값이 대입되며 print(a)에 의해서 아래와 같이 그 값이 차례대로 출력된다. 

In [20]:
# 리스트 활용 
for x in [1, 2, 3]: # 리스트의 요소들을 하나씩 x에 대입
    print(x)

1
2
3


In [21]:
# 튜플 활용 
for x in (1, 2, 3): 
    print(x)

1
2
3


아래와 같이 for문 안에 if 문을 사용 할 수 있다. 

In [22]:
for i in [1, 2, 3, 4, 5]:
    if i%2 == 0:     
        print(i, '는 2의 배수')
    elif i%3 == 0:
        print(i, '는 3의 배수')
    else:
        pass   # 수행 없음 

2 는 2의 배수
3 는 3의 배수
4 는 2의 배수


### range 함수  사용
* for문은 숫자 리스트를 자동으로 만들어 주는 range 함수와 함께 사용하는 경우가 많다. 다음은 range 함수의 간단한 사용법이다.

In [23]:
# range(11)은 0이상 11 미만의 숫자를 포함하는 객체를 만들어 준다.
a = range(11)
a 

range(0, 11)

In [24]:
# 시작 숫자와 끝 숫자를 지정하려면 range(시작 숫자, 끝 숫자) 형태를 사용한다. (0이상 11미만의 숫자를 포함하는 객체)
b = range(0, 11)

In [25]:
b

range(0, 11)

In [26]:
a == b

True

In [27]:
for i in range(6):
    print(i)

0
1
2
3
4
5


for 문에서 사용되는 range 함수의 예시를 좀 더 살펴보자

for와 range 함수를 사용하면 1부터 10까지 더하는 것을 다음과 같이 쉽게 구현할 수 있다.

In [28]:
add = 0
for i in range(1, 11):
    add = add+i   # 1 이상 11 미만의 숫자가 이전 add에 계속 더해짐 
print(add)

55


### for문 중첩 사용

* for와 range 함수를 사용하면 소스 코드 단 4줄만으로 구구단을 출력할 수 있다.

In [29]:
for i in range(2, 10): # ①번 for문
    for j in range(1, 10): # ②번 for문
        print(i*j, end=" ") # end를 넣어 준 이유는 해당 결괏값을 출력할 때 다음줄로 넘기지 않고 그 줄에 계속해서 출력하기 위해
    print('') # 2단, 3단 등을 구분하기 위해 두 번째 for문이 끝나면 결괏값을 다음 줄부터 출력하게 해주는 문장

2 4 6 8 10 12 14 16 18 
3 6 9 12 15 18 21 24 27 
4 8 12 16 20 24 28 32 36 
5 10 15 20 25 30 35 40 45 
6 12 18 24 30 36 42 48 54 
7 14 21 28 35 42 49 56 63 
8 16 24 32 40 48 56 64 72 
9 18 27 36 45 54 63 72 81 


### 반복문 while

- While이라는 영어 단어는 "~인 동안"이란 뜻인데, for문과 마찬가지로 반복해서 문장을 수행할 수 있도록 해준다.

* 다음은 while 반복문의 기본구조이다. 
* while문은 조건문이 참인 동안에 while문 아래의 수행할 문장이 반복해서 수행된다.

while 조건문:

    수행할 문장1
    수행할 문장2
    수행할 문장3
    ...

In [30]:
# i < 5 인 동안에 i 를 출력하고 i+1 로 i를 재정의 함 
i=0
while i<5:
    print(i)
    i = i+1   # i+=1  도 동일한 표현, 
              # i=i+1이라는 문장은 i의 값을 1씩 더하게 한다. 
              # i 값이 5보다 커지게 되면 while문을 빠져나가게 된다.

0
1
2
3
4


In [31]:
# treeHit <10 인 동안에 treeHit을 하나씩 키우면서, 첫번쨰 print 내용을 출력하고, treeHit 이 10이 되면 "나무 넘어갑니다" 출력
treeHit = 0

while treeHit<10:
    treeHit = treeHit+1
    print("나무를 %d번 찍었습니다." % treeHit)
    if treeHit==10:
        print("나무 넘어갑니다.")

나무를 1번 찍었습니다.
나무를 2번 찍었습니다.
나무를 3번 찍었습니다.
나무를 4번 찍었습니다.
나무를 5번 찍었습니다.
나무를 6번 찍었습니다.
나무를 7번 찍었습니다.
나무를 8번 찍었습니다.
나무를 9번 찍었습니다.
나무를 10번 찍었습니다.
나무 넘어갑니다.


## 함수 만들기

- 파이썬은 def 를 통해 사용자가 원하는 기능을 하는 함수를 직접 만들 수 있다. 
- def 는 파이썬에서 함수를 만들어 주는 문법 단어 (예약어)이다.

기본 형식은 다음과 같다.

In [ ]:
def 이름(입력 변수):  
    실행 문장  
    return 출력 변수

아래 예제는 add 함수를 만들고 그 함수를 어떻게 사용하는지를 보여준다. 

In [32]:
# add(a, b)에서 a, b는 입력값이고, a+b는 결괏값이다. 즉 1, 2가 입력으로 들어오면 1+2를 수행하고 그 결괏값인 3을 돌려준다
def add(a,b):
    return a+b

add(1,2)

3

In [33]:
## print와 return의 차이: return을 해야 저장됨
def sum1(a,b):
    print(a+b)
 
b = sum1(1,2)

3


In [34]:
print(b)

None


<hr>

# 자료의 형태(Data type)

## 숫자형 자료 (numeric)

- 숫자형(Number)이란 숫자 형태로 이루어진 자료형으로, 
  - 형태에 따라서 1, 2, 3 과 같은 정수(interger),
  - 12.34 와 같은 실수(float), 
  - 드물게 사용하는 복소수(complex)로 구분하여 생각할 수 있다.
- 이들을 활용한 다양한 연산이 가능하다.
- type(변수명) 함수는 type을 출력하는 함수로, 해당 변수의 자료형을 확인할 수 있다.

In [35]:
a=5
b=3

c=a+b

print(c)

8


In [36]:
type(a) # 정수

int

## 문자열 자료(string)

- 문자열(String)이란 문자, 단어 등으로 구성된 문자들의 집합을 의미한다. 
- 문자형 자료의 입력은 작은 따옴표(‘ ’) 또는 큰 따옴표(“ ”)를 사용한다. 

In [37]:
d='python'; print(d)
e="python"; print(e)
f="'python'";print(f)

python
python
'python'


In [38]:
g="123";print(g)

123


"123은 숫자인데 왜 문자열이지?"라는 의문이 들수도 있으나 따옴표로 둘러싸여 있으면 모두 문자열 자료형이라고 보면 된다.

### 문자열 포맷팅 (fomatting) 
* 문자열에서 특정 값을 변경하려면 formatting을 사용한다. 
* 아래 예제와 같이 문자열 안의 특정한 값 만을 바꿔야 할 경우가 있을 때 이것을 가능하게 해주는 것이 바로 문자열 포매팅 기법이다.

In [39]:
"I ate %d apples. so I was sick for %d days."  % (15, 2) #  %d : 정수(Integer)

'I ate 15 apples. so I was sick for 2 days.'

### format 함수를 사용한 포맷팅
* format 함수를 사용한 포맷팅도 가능하다. 앞에서 살펴본 문자열 포매팅 예제를 format 함수를 사용해서 바꾸면 다음과 같다.

In [40]:
# .format() 함수 사용
"I ate {0} apples. so I was sick for {1} days.".format(15,2)

'I ate 15 apples. so I was sick for 2 days.'

## 논리형 자료

- 불(bool) 자료형이란 참과 거짓을 나타내는 논리 유형을 나타내는 자료형이다. 
- 파이썬에서는 비교 연산자와 논리 연산자의 판단 결과로 참 또는 거짓을 사용한다.

In [41]:
a=1
b= (a==1) # 비교를 위한 연산자

print(b)
print(a>2)

True
False


## 리스트(List) 자료형

- 리스트는 여러 개의 값을 일렬로 늘어놓아 묶어 놓은 집합체이다. 
- 변수에 값을 저장할 때, 여러 개의 값을 대괄호([ ])로 묶어주면 리스트가 되며 각 값은 comma(,) 로 구분할 수 있다. 
- 리스트에 저장된 각각의 값은 요소(element)라고 부르며 리스트는 숫자형, 문자형, 논리형 등 모든 자료형을 저장할 수 있으며 자료형을 섞어서 저장할 수도 있다.

In [42]:
# 리스트는 다양한 유형의 요소를 지닐 수 있음 (비어있는 리스트, 숫자형, 문자열, 리스트 등...) 
a = [2,4,6,8]
b = [1, "I", 30, "Love"]
c = [1, "I", [2, "Love"]]
d = [1, "I", [2, "Love", [3, "You"]]]
e = []  

print(a,b,c,d,e)

[2, 4, 6, 8] [1, 'I', 30, 'Love'] [1, 'I', [2, 'Love']] [1, 'I', [2, 'Love', [3, 'You']]] []


In [43]:
aa=[[0,1,2,3],
   [4,5,6,7],
   [8,9,10,11]]
print(type(aa),aa)

<class 'list'> [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


### 리스트 관련 함수

- 리스트 변수 이름 뒤에 '.'를 붙여서 여러 가지 리스트 관련 함수를 사용할 수 있다.

* 함수 

|Operation    | Description |
|:--------:| :----:|
| x.append()	| 요소 추가 : 리스트 x의 마지막 요소 추가  |
| x.sort()      | 리스트 정렬 : 리스트 x 의 요소를 순서대로 정렬|
| x.reverse()	| 리스트 뒤집기 : 현재 리스트 x의 요소를 거꾸로 뒤집기  |
| x.index(a)  | 위치 반환 : 리스트 x에 a 값이 있으면 위치를 반환 |
| x.insert(a,b) | 요소 삽입 : 리스트 x의 a 번째 위치에 b를 삽입|
| x.remove(a)   | 요소 제거 : 리스트 x에서 첫번째로 나타나는 a를 삭제 |
| x.pop()       | 요소 끄집어내기 : 리스트 x의 마지막 요소(혹은 위치 지정가능)를 반환하고 그 요소를 삭제 |
| x.count(a)    | 갯수세기 : 리스트 x 안에 a가 몇개 있는지 갯수 반환 |
| x.extend(a)   | 리스트 확장: 리스트 x에 리스트 a를 더함 |
| x.copy()   | 리스트 복사: 리스트 x를 복사 |

In [44]:
List = ["A", "B", "C", "D"]

In [45]:
# append: 요소 값 추가
List.append("E")   
print(List)

# extend : 리스트 추가(확장)
List.extend(["G","H"]) 
print(List)

b= ["I", "J"]
List.extend(b)
print(List)

# insert : 요소 삽입
List.insert(5, "F") #  index 5(0부터 시작)에 "F" 삽입
print(List)

['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D', 'E', 'G', 'H']
['A', 'B', 'C', 'D', 'E', 'G', 'H', 'I', 'J']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']


## 딕셔너리(Dictionary) 자료형

* 딕셔너리는 사전 처럼 대응관계를 나태날 수 있는 자료형이다.
   - "apple" 라는 단어에 사과, "love" 라는 단어에 "사랑" 이라는 뜻이 대응되듯 딕셔러니 자료는 key 와 value를 한 쌍으로 갖는 자료형이다.  key 가 love 라고 한다면, value는 "사랑" 이 될 것이다.  

  
* 리스트나 튜플과의 차별점
   - 리스트와 튜플은 순차적으로 요소 값을 모두 확인하지만, 딕셔너리는 Key를 통해서 바로 value를 확인한다. 예를 들어, love의 뜻을 찾기 위해서 사전의 처음 부터 순차적으로 모두 검색하는 것이 아니라, love 라는 단어가 있는 곳만 확인하는 것이다. 
   
   
* 따라서, key는 고유한 값(중복되지 않아야 함)이어야 하며, 문자열 또는 단일 숫자, 튜플과 같이 변하지 않는 값인 unhashable type이어야 한다. 리스트와 같이 변경이 가능한 값은 Key로 사용이 불가능하다. 
* Value는 중복된 값이 사용 될 수 있으며, 변하는 값이든 변하지 않는 값이든 아무 값이나 넣을 수 있다. 


* 즉, 딕셔너리는 Index가 아닌 Key를 사용하여 데이터 탐색 하고
* 순서가 없는 자료형으로 Indexing과 slicing이 불가하다.




* 딕셔너리는 아래와 같이 중괄호 { }로 묶어서 표현 한다. 

{Key1:Value1, Key2:Value2, Key3:Value3, ...}

In [46]:
# example 
dic = {'Name':'James', 'Job':'Student', 'Phone':[82,10,9994,323]} # Key (Name , job , Phone) , value 
print(dic)
print(dic['Name'] + ' is a ' + dic['Job'])

{'Name': 'James', 'Job': 'Student', 'Phone': [82, 10, 9994, 323]}
James is a Student


In [47]:
type(dic)

dict

### 딕셔너리 추가와 삭제

#### 딕셔너리 key & value  추가 

In [48]:
dic = {'Name':'James', 'Job':'Student'}
dic['Phone'] = [82,10,9994,323]  # key & value 삽입
print(dic)


{'Name': 'James', 'Job': 'Student', 'Phone': [82, 10, 9994, 323]}


In [49]:
dic[1] ="a" # key & value 삽입
print(dic)

{'Name': 'James', 'Job': 'Student', 'Phone': [82, 10, 9994, 323], 1: 'a'}


#### 딕셔너리 삭제

In [50]:
del dic['Phone'] # key & value 삭제
print(dic)

{'Name': 'James', 'Job': 'Student', 1: 'a'}


In [51]:
del dic[1]  # Index 가 아닌 key 를 찾아 삭제한다 (딕셔너리는 순서가 없는 자료형 )
print(dic)

{'Name': 'James', 'Job': 'Student'}


### 딕셔너리 관련 함수 

* 함수 

|Operation    | Description |
|:--------:   | :----------:|
| x.keys()      | Key 리스트 만들기 |
| x.values()    | Value 리스트 만들기 |
| x.items()	    | Key, Value 쌍 얻기  |
| x.clear()     | Key: Value 쌍 모두 지우기 |
| x.get(a)      | Key a에 해당 하는 Value얻기|
| a in x        | key a가 딕셔너리 x 안에 있는지 확인 (True/ False) |


In [52]:
dic = {'Name':'James', 'Job':'Student',  'Phone': [82, 10, 9994, 323]}
print(dic.keys()) # key를 리스트로 묶어 dict_key 객체로 돌려줌 
print(dic.values()) # value를 리스트로 묶어 dict_values 객체로 돌려줌 
print(dic.items()) # key & value 쌍을 튜플로 묶어 dict_items로 돌려줌
print(dic.get('Name')) # key 값을 이용해 value 출력
print(dic['Name']) # 위와 동일
print('Job' in dic) # 해당 값을 지닌 key 존재 여부 확인
print('ID' in dic)
dic.clear() # 전체 삭제
print(dic)

dict_keys(['Name', 'Job', 'Phone'])
dict_values(['James', 'Student', [82, 10, 9994, 323]])
dict_items([('Name', 'James'), ('Job', 'Student'), ('Phone', [82, 10, 9994, 323])])
James
James
True
False
{}


* Tip : Key 가 중복된 경우 어떻게 될까? 

    * 이 경우 중복된 key가 사용된 경우 하나만 사용하고 나머지는 버린다. 
    
    * 어떤 value를 사용하고, 어떤 value를 버릴지 알 수 없음(random하게 선택 됨)

In [53]:
dic = {'Name':'James', 'Name':'SJ', 'Job':'Student'}
print(dic)

{'Name': 'SJ', 'Job': 'Student'}


# 인덱싱(Indexing)과 슬라이싱(Slicing)

- 인덱싱(Indexing)이란 무엇인가를 "가리킨다"는 의미이고, 슬라이싱(Slicing):은 무엇인가를 "잘라낸다"는 의미이다.
  - 인덱싱은 자료의 위치에 번호를 매겨 출력한 것이다.
  - 주의할 점은 파이썬은 0 부터 번호를 매긴다는 점이다.
    
  - 자료[번호]는 문자열 안의 특정한 값을 뽑아내는 역할을 하며, 이러한 작업을 인덱싱이라고 한다.
  - "Life is too short, You need Python"에서 단순히 한 문자만을 뽑아내는 것이 아니라 'Life' 또는 'You' 같은 단어를 뽑아내는 방법이 슬라이싱이다.  

- 문자형, array, series, list, dataframe 등에서 사용이 가능
  - dataframe에서는 행, 열의 사용 방법이 상이

### list 자료형과 인덱싱

In [54]:
a = [2,4,6,8]
b = [1, "I", 30, "Love"]
c = [1, "I", [2, "Love"]]
d = [1, "I", [2, "Love", [3, "You"]]]

In [55]:
print("List Index")
print(a[0])
print(a[1])
print(a[-1])
print(a[-2])
print(b[2])
print(c[2])
print(c[2][1])
print(d[-1])

List Index
2
4
8
6
30
[2, 'Love']
Love
[2, 'Love', [3, 'You']]


In [56]:
print(a[0]+a[1])
print(b[1]+b[3])

6
ILove


In [57]:
print("List Slicing")
x = "Life is too short, You need Python"

print(x[0:4]) #슬라이싱
# 참고로
print(x[0]) # 인덱싱

List Slicing
Life
L


위의 문자열에서 단순히 한 문자만을 뽑아내는 것이 아니라 'Life' 또는 'You' 같은 단어를 뽑아내는 방법이 슬라이싱이다.

In [58]:
print(a[0:2])
print(c[1:2])
print(c[1:-1])
print(d[1:])

[2, 4]
['I']
['I']
['I', [2, 'Love', [3, 'You']]]


In [59]:
print(aa[0])
print(aa[0][1]) # aa의 [0]에서 [1]번째, 행,열로 이해X
print(aa[2][3])
#print(aa[1,1]) # error

[0, 1, 2, 3]
1
11


## 배열(array)

- 백터와 행렬 만들기
- 리스트는 속도가 느리고 메모리를 많이 차지하는 단점이 있다. 
- 배열(array)을 사용하면 적은 메모리로 많은 데이터를 빠르게 처리할 수 있다. 
- 배열은 리스트와 비슷하지만 다음과 같은 점에서 다르다.
  - 모든 원소가 같은 자료형이어야 한다.
  - 원소의 갯수를 바꿀 수 없다.
- 파이썬은 자체적으로 배열 자료형을 제공하지 않는다. 파이썬에서 배열을 사용하기 위한 표준 패키지는 넘파이(numpy)다.

In [60]:
import numpy as np

x=np.array(range(16))
print(x)
type(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


numpy.ndarray

In [61]:
x=np.reshape(x,(4,4)) # matrix
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### array 인덱싱

In [62]:
print(x)
print(x[0])
print(x[0:3,1:4])
print(x[:,0:2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [63]:
print(x[0][1],x[0,1]) # 같은 결과 # 리스트에서는 x[0,1] 불가능

1 1


## Series 자료

- Series란 일련의 객체를 담을 수 있는 1차원 배열(array)와 같은 구조이다.  
- Series는 서로 다른 자료형(type)을 동시에 가질 수 있다.
- Data Frame을 구성하는 하나의 특정 행이나 열로 설명 가능하며, Data Frame의 기본형이라 생각할 수 있다. (Series가 모여 Data Frame이 만들어짐)
- pandas 패키지에서 Series 와 DataFrame 이라는 대표적인 두 가지 구조를 제공한다.

### Series 생성

In [64]:
from pandas import Series, DataFrame

In [65]:
obj1 = Series([1, 'A', True])
obj1

0       1
1       A
2    True
dtype: object

In [31]:
obj2 = Series([4, 7, -5, 3])
obj2

0    4
1    7
2   -5
3    3
dtype: int64

* Python의 기본 자료형인 딕셔너리(dictionary)를 통해 Series를 생성할 수 있다.

In [32]:
sdata = {'Utah' : 35000, 'Oregon' : 71000, 'Texas' : 16000, 'Ohio': 5000}
obj3 = Series(sdata) 
obj3   # key 이름 기준으로 정렬되는 것 확인

Utah      35000
Oregon    71000
Texas     16000
Ohio       5000
dtype: int64

### 색인(index)

Series의 중요한 특징 중 하나는 색인(index)을 가지고 있다.(cf.Dataframe)

In [66]:
obj4 = Series([4, 7, -5, 3], index=['a', 'b', 'c', 'd'])
obj4

a    4
b    7
c   -5
d    3
dtype: int64

* Series의 요소 값(values)와 색인(index)는 values, index 속성을 통해 각각 얻을 수 있다.

In [67]:
print(obj4.values) # 객체 값들만 반환
print(obj4.index)  # 색인(index)만 반환
print(obj4.dtypes) # 자료형

[ 4  7 -5  3]
Index(['a', 'b', 'c', 'd'], dtype='object')
int64


### Series 인덱싱

* Series의 index 위치나 조건을 가지고 indexing 을 해보겠습니다.

In [68]:
obj4[0]

4

In [69]:
obj4[:3]

a    4
b    7
c   -5
dtype: int64

In [70]:
obj4[obj4 >= obj4.mean()]

a    4
b    7
d    3
dtype: int64

In [71]:
# 특정 index label을 지정해서 indexing을 해보겠습니다.
obj4[['a']]

a    4
dtype: int64

In [72]:
obj4[['a','b']]

a    4
b    7
dtype: int64

In [73]:
# 특정 index label 을 지정해서 값(value)을 할당해보겠습니다.
obj4[['a']]=100
obj4

a    100
b      7
c     -5
d      3
dtype: int64

In [74]:
# 특정 index label 이 Series에 들어있는지 아닌지 확인 (boolean True, False) 해보겠습니다
'a' in obj4


True

In [75]:
7 in obj4

False

## dataframe 자료형

- DataFrame은 데이터를 담는 틀(frame)으로 행렬(matrix)와 유사한 구조를 가진다.
- 즉, 2차원의 구조로 행(row)과 열(column)으로 이루어져 있다.
- 변수(variable) 
  - 데이터프레임의 한 열(column)로서 구체적인 속성을 나타내는 자료값들의 집합
  - 문자, 숫자, 특수문자 및 기호 등으로 이루어진 문자형(character type) 변수와 숫자만으로 이루어진 숫자형(numeric type)변수로 분류됨
- 개체(observation) : 데이터프레임의 한 행(row)으로서 동일한 관찰단위에 대한 모든 변수들의 자료값들의 집합

### dataframe 만들기

 DataFrame을 생성하는 가장 기본적인 두 가지 방법은 같은 길이의 리스트(list)가 담긴 사전형(dictionary) 와 Numpy의 배열(array)를 이용하는 것이다. 

In [77]:
data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year' : [2000, 2001, 2002, 2001, 2002],
        'pop' : [1.5, 1.7, 3.6, 2.4, 2.9]}
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [98]:
frame = DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [78]:
DataFrame(data, columns = ['year', 'pop', 'state']) # 순서 바꾸기

year  pop   state
0  2000  1.5    Ohio
1  2001  1.7    Ohio
2  2002  3.6    Ohio
3  2001  2.4  Nevada
4  2002  2.9  Nevada

In [79]:
frame2 = DataFrame(data, index=['one', 'two', 'three', 'four', 'five']) # index 설정
frame2

state  year  pop
one      Ohio  2000  1.5
two      Ohio  2001  1.7
three    Ohio  2002  3.6
four   Nevada  2001  2.4
five   Nevada  2002  2.9

* DataFrame.index 로 index 확인, DataFrame.columns 로 칼럼 확인할 수 있습니다.

In [80]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [81]:
frame2.columns

Index(['state', 'year', 'pop'], dtype='object')

 * 기존 데이터프레임에서 행과 열을 선별해서 새로운 DataFrame을 만들 수 있습니다.

In [82]:
DataFrame(frame2, index=['one', 'two'], columns=['state', 'year'])

state  year
one  Ohio  2000
two  Ohio  2001

- DataFrame에서 칼럼 이름을 지정해서 선별하는 방법

In [83]:
frame2[['state','pop']]

state  pop
one      Ohio  1.5
two      Ohio  1.7
three    Ohio  3.6
four   Nevada  2.4
five   Nevada  2.9

- DataFrame의 각 열을 지정해서 불러오는 방법

In [84]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [85]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [86]:
frame2[['state']]

state
one      Ohio
two      Ohio
three    Ohio
four   Nevada
five   Nevada

- DataFrame에 새로운 칼럼을 만들기

In [87]:
frame2['new']=frame2['year']+frame2['pop']
frame2

state  year  pop     new
one      Ohio  2000  1.5  2001.5
two      Ohio  2001  1.7  2002.7
three    Ohio  2002  3.6  2005.6
four   Nevada  2001  2.4  2003.4
five   Nevada  2002  2.9  2004.9

In [88]:
frame2 = frame2.assign(new2 =  frame2['pop']* frame2['pop'])
frame2

state  year  pop     new   new2
one      Ohio  2000  1.5  2001.5   2.25
two      Ohio  2001  1.7  2002.7   2.89
three    Ohio  2002  3.6  2005.6  12.96
four   Nevada  2001  2.4  2003.4   5.76
five   Nevada  2002  2.9  2004.9   8.41

* Numpy 배열 객체로도 DataFrame을 생성할 수 있다.

In [89]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
np.array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
num = DataFrame(np.arange(9).reshape(3, 3),
                index=["a", "b", "d"], 
                columns=["x", "y", "z"])
num

x  y  z
a  0  1  2
b  3  4  5
d  6  7  8

- DataFrame의 칼럼을 삭제하는 방법에는 다음의 두가지 방법이 있습니다.
  1. df.drop(['xx', 'xx']
  2. del df['xx'] :  원본 데이터프레임에서 칼럼을 삭제합니다.

In [93]:
frame2.drop(['new2'],axis=1) #  axis=0은 행, axis=1은 열을 기준으로 삭제

state  year  pop     new
one      Ohio  2000  1.5  2001.5
two      Ohio  2001  1.7  2002.7
three    Ohio  2002  3.6  2005.6
four   Nevada  2001  2.4  2003.4
five   Nevada  2002  2.9  2004.9

In [94]:
frame2

state  year  pop     new   new2
one      Ohio  2000  1.5  2001.5   2.25
two      Ohio  2001  1.7  2002.7   2.89
three    Ohio  2002  3.6  2005.6  12.96
four   Nevada  2001  2.4  2003.4   5.76
five   Nevada  2002  2.9  2004.9   8.41

In [95]:
del frame2['new2']

In [96]:
frame2

state  year  pop     new
one      Ohio  2000  1.5  2001.5
two      Ohio  2001  1.7  2002.7
three    Ohio  2002  3.6  2005.6
four   Nevada  2001  2.4  2003.4
five   Nevada  2002  2.9  2004.9

### 데이터 프레임 관련 유용한 함수

- 데이터프레임에 관한 정보를 얻기에 유용한 함수
- dataframe 이름: df
    
|Operation    | Description |
|:--------:| :----:|
| df.head(n)	|  데이터 프레임에서 상위 n개의 행을 보여줌. (default n=5)|
| df.tail(n)	| 데이터 프레임에서 하위 n개의 행을 보여줌. (default n=5)|
| df.shape	| 데이터 프레임의 (행,열)의 개수 |
| df.info( )	| 데이터 프레임의 기본 정보 출력(각 칼럼 별 데이터 수, 데이터 타입)|
| df.describe()	| 수치형 변수들의 기초 통계량 값 제공|
| df.columns	| 데이터 프레임에 어떤 column이 있는지 보여줌|
| df['칼럼 명'].dtype| 특정 칼럼의 데이터 타입 확인|
| df["칼럼 명"].unique()| 특정 칼럼에 있는 데이터들의 유일한 값|
| df["칼럼 명"].nunique()| 특정 칼럼에 있는 데이터들의 유일한 값의 갯수|

In [99]:
frame.head() # 데이터 프레임에서 상위 n개의 행을 보여줌. (default n=5)

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [100]:
frame.tail(2) # 데이터 프레임에서 하위 n개의 행을 보여줌. (default n=5)

state  year  pop
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [101]:
frame.shape # 데이터 프레임의 (행,열)의 개수 

(5, 3)

In [102]:
frame.info( ) # 데이터 프레임의 기본 정보 출력(각 칼럼 별 데이터 수, 데이터 타입)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   state   5 non-null      object 
 1   year    5 non-null      int64  
 2   pop     5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 248.0+ bytes


In [103]:
frame.describe() # 수치형 변수들의 기초 통계량 값 제공

year       pop
count     5.00000  5.000000
mean   2001.20000  2.420000
std       0.83666  0.864292
min    2000.00000  1.500000
25%    2001.00000  1.700000
50%    2001.00000  2.400000
75%    2002.00000  2.900000
max    2002.00000  3.600000

In [104]:
frame.columns #데이터 프레임에 어떤 column이 있는지 보여줌

Index(['state', 'year', 'pop'], dtype='object')

In [105]:
frame['pop'].dtype # 특정 칼럼의 데이터 타입 확인

dtype('float64')

In [106]:
frame["year"].unique() # 특정 칼럼에 있는 데이터들의 유일한 값

array([2000, 2001, 2002], dtype=int64)

In [77]:
frame["year"].nunique() # 특정 칼럼에 있는 데이터들의 유일한 값의 갯수

3

### dataframe의 인덱싱

* DataFrame의 행(row)과 열(column)을 선택

  1. Selecting column form DataFrame

In [107]:
frame2['state'] 

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [108]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

  2. selecting row from DataFrame

In [109]:
frame2[0:2] 

state  year  pop     new
one  Ohio  2000  1.5  2001.5
two  Ohio  2001  1.7  2002.7

In [110]:
frame2['state'][0:2] # indexing 'column' and 'row' from DataFrame

one    Ohio
two    Ohio
Name: state, dtype: object

In [111]:
frame2.state[0:2]

one    Ohio
two    Ohio
Name: state, dtype: object

- 조건을 부여해서 열을 선택할 수도 있습니다.

In [112]:
frame2[frame2['year'] <= 2001]

state  year  pop     new
one     Ohio  2000  1.5  2001.5
two     Ohio  2001  1.7  2002.7
four  Nevada  2001  2.4  2003.4

In [114]:
frame2[1,0:2]  # error, loc와 iloc를 사용해서 인덱싱 해야됨

InvalidIndexError: (1, slice(0, 2, None))

In [85]:
frame2[1,"state"] # error, loc와 iloc를 사용해서 인덱싱 해야됨

KeyError: (1, 'state')

## loc와 iloc를 사용해서 인덱싱과 슬라이싱하기

- loc, iloc의 두가지 방법    

- loc: (location) 우리가 설정한 인덱스(행 기준)이나 column(열) 이름을 이용해 subdata를 출력한다.  
    (Boolean을 입력값으로 받을 수도 있다. 인덱스는 디폴트로 0,1,2,...도 가능)
  - row 선택
      - df.loc["인덱스 이름"] : 단일 label로 row 선택. Series로 나옴
      - df.loc[["인덱스 이름1","인덱스 이름2"]] : list나 array로 row 선택        
      - df.loc[:"인덱스 이름"] : slice로 row 선택    
  - row, column 선택  
      - df.loc[["인덱스 이름"], ["칼럼 이름"]]   
  - column 선택  
      - df.loc[:, ["칼럼 이름"]]     

- iloc: (integer location) DataFrame에 저장되어 있는 고유 인덱스 번호(정수)로 인덱싱과 슬라이싱 
  - row 선택   
      - df.iloc[2] : 단일 label로 row 선택
      - df.iloc[[0,1,2]] : list나 array로 row 선택
      - df.iloc[0:2] : slice로 row 선택
  - column 선택    
      - df.iloc[:, 0:2]

### loc 사용하기

#### row 선택

In [115]:
frame2.loc[['one','two']] # df.loc["인덱스 이름1", "인덱스 이름2"]

state  year  pop     new
one  Ohio  2000  1.5  2001.5
two  Ohio  2001  1.7  2002.7

기본적으로 .loc과 iloc을 사용해 single column을 불러오면 Series 형식으로 저장된다. 이를 Dataframe 형태로 불러오기 위해 list를 사용한다. 

In [116]:
frame.loc[1] # Series로 나옴, 인덱스 이름이 없는 경우 

state    Ohio
year     2001
pop       1.7
Name: 1, dtype: object

In [117]:
frame.loc[[1]]  # [[""]]:DataFrame으로 나옴, 

# frame2.loc[[1]] 는 error   #  frame2는 인덱스가 "one", "two",...

state  year  pop
1  Ohio  2001  1.7

In [118]:
frame.loc[1:2] 

state  year  pop
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [119]:
frame.loc[[1,2]]

# frame2.loc[1:2] # error. # frame2는 인덱스가 "one", "two",...

state  year  pop
1  Ohio  2001  1.7
2  Ohio  2002  3.6

#### row, column 선택

In [120]:
frame.loc[[1],["state"]] # df.loc[["인덱스 이름"], ["칼럼 이름"]]   # DataFrame으로 나옴, 

state
1  Ohio

In [121]:
frame.loc[1,"state"] # df.loc["인덱스 이름", "칼럼 이름"]  # Series 출력

'Ohio'

In [122]:
frame.loc[1:2,["state","pop"]]

state  pop
1  Ohio  1.7
2  Ohio  3.6

#### column 선택

In [123]:
frame.loc[:,["state","pop"]] # 행만 선택

state  pop
0    Ohio  1.5
1    Ohio  1.7
2    Ohio  3.6
3  Nevada  2.4
4  Nevada  2.9

### iloc 사용하기

* index의 label 이 아니라 정수(integer)로 indexing을 하려면 df.iloc[int] 를 사용해야 합니다. 
* 만약 df.loc[int]를 사용하면 TypeError 가 발생합니다.

#### row 선택

In [124]:
frame2.iloc[0]

state      Ohio
year       2000
pop         1.5
new      2001.5
Name: one, dtype: object

In [125]:
frame2.iloc[0:2]  

state  year  pop     new
one  Ohio  2000  1.5  2001.5
two  Ohio  2001  1.7  2002.7

#### column 선택

* DataFrame의 행(row) indexing할 때 df[0:2] 처럼 행의 범위를 ':'로 설정해주어도 됩니다. 
* df[0] 처럼 정수값을 지정하면 KeyError 납니다(이때는 df.iloc[0] 을 써야 함)

In [126]:
frame2.iloc[:,0:2] 

# frame2[:,0:2]  # error 

state  year
one      Ohio  2000
two      Ohio  2001
three    Ohio  2002
four   Nevada  2001
five   Nevada  2002

In [127]:
frame.iloc[:,-1] # Series

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
Name: pop, dtype: float64

In [128]:
frame2.iloc[:,[-1]] # DataFrame

new
one    2001.5
two    2002.7
three  2005.6
four   2003.4
five   2004.9

In [129]:
frame2.iloc[:,[0,2]] # 특정 column

state  pop
one      Ohio  1.5
two      Ohio  1.7
three    Ohio  3.6
four   Nevada  2.4
five   Nevada  2.9

### .iloc을 사용해 Label 값으로 Indexing 하기

- 때론 위치와 값을 혼횽해야 할 때가 있다. 
- 예를들어 (어떤 이유로) row는 index값으로, column은 위치로 subdata를 불러와야 한다면, Dataframe의 .get_loc을 활용할 수 있다. 
- .get_loc은 해당값의 위치를 반환하기 때문에 .iloc의 입력값으로도 사용할 수 있다. 
- index와 column 둘 다 사용할 수 있으며 예시는 아래와 같다.

In [132]:
# get_loc 사용하기: row
print(frame2.index.get_loc('two'))
frame2.iloc[frame2.index.get_loc('two')] #.iloc의 입력값으로도 사용

1


state      Ohio
year       2001
pop         1.7
new      2002.7
Name: two, dtype: object

In [133]:
# get_loc 사용하기: column
print(frame2.columns.get_loc('state'))
frame2.iloc[:,frame2.columns.get_loc('state')] #.iloc의 입력값으로도 사용

0


one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

## at, iat 사용

- it, iat: 정확한 위치의 값을 요청하는 방법
  - cf) loc, iloc는 인덱스에 따른 모든 컬럼의 값을 가져오는데에 초점이 맞춰져 있다.   

- at: 지정한 인덱스를 이용해 원하는 위치값을 가져올 수 있다.(콕 집어서 하나의 값만 가져옴)
  - df.at[index,column]      
    
- iat: 고유하게 정해지는 row_number,  column_number로 위치를 지정해 가져올 수 있다.
  - df.iat[row\_number, column_number] 

In [134]:
frame.at[1,"state"]

'Ohio'

In [135]:
frame.iat[1,2]

1.7

<hr>

# 내장함수와 라이브러리

## 다양한 내장함수

In [136]:
"""
abs(x) :절대값
"""
abs(-1.2)

1.2

In [137]:
"""
len
len(s)은 입력값 s의 길이(요소의 전체 개수)를 돌려주는 함수
"""
print(len("python"))
print(len([1,2,3]))
print(len((1,"a")))

6
3
2


In [138]:
"""
range
range([start,] stop [,step] )는 for문과 함께 자주 사용하는 함수
"""
print(list(range(5)))        # 0이상 5미만의 정수
print(list(range(5, 10)))    # 5이상 10미만의 정수
print(list(range(1, 10, 2))) #1부터 10미만까지 2 만큼의 간격의 숫자 

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]


In [128]:
range(5)

range(0, 5)

In [129]:
list(range(5))

[0, 1, 2, 3, 4]

In [130]:
"""
round
round(number[, ndigits]) 함수는 숫자를 입력받아 반올림해 주는 함수
round 함수의 두 번째 매개변수는 반올림하여 표시하고 싶은 소수점의 자릿수
"""
print(round(4.6))
print(round(5.678, 2)) # 소수점 2자리까지만 반올림하여 표시

5
5.68


In [131]:
"""
sorted
sorted(iterable) 함수는 입력값을 정렬한 후 그 결과를 리스트로 돌려주는 함수
"""
print(sorted(['a', 'c', 'b']))
print(sorted((3, 2, 1)))
print(sorted("zero"))

['a', 'b', 'c']
[1, 2, 3]
['e', 'o', 'r', 'z']


In [132]:
"""
list
list(s)는 반복 가능한 자료형 s를 입력받아 리스트로 만들어 돌려주는 함수
"""
print(list("python"))
print(list((1,2,3)))

['p', 'y', 't', 'h', 'o', 'n']
[1, 2, 3]


In [133]:
"""
type
type(object)은 입력값의 자료형이 무엇인지 알려 주는 함수
"""
print(type("abc"))
print(type([ ]))   

<class 'str'>
<class 'list'>


In [135]:
"""
del 함수를 이용한 요소 삭제
"""

a = [1, 2, 3]
del a[2]
a

[1, 2]

In [138]:
"""
sum
sum(iterable) 은 입력받은 리스트나 튜플의 모든 요소의 합을 돌려주는 함수
"""
sum([1,2,3])

6

In [113]:
"""
dir
dir(): 작업공간에 대기하고 있는 객체들의 목록 출력
dir(): ()안에 아무것도 넣지 않으면 기본적으로 현재 메모리에 할당되어 있는 변수들을 볼 수 있는 함수이다.
dir(*): ()안에 Class나 함수의 이름을 그대로 넣으면 함수에 대한 명령어의 목록을 얻을 수 있는 함수이다. 전체적으로 어떤 기능들이 있는지 훑어볼 때 유용하다.
"""
dir()

['DataFrame',
 'In',
 'Out',
 'Series',
 '_',
 '_1',
 '_101',
 '_104',
 '_105',
 '_106',
 '_107',
 '_108',
 '_109',
 '_110',
 '_112',
 '_13',
 '_14',
 '_2',
 '_23',
 '_30',
 '_31',
 '_32',
 '_33',
 '_34',
 '_35',
 '_37',
 '_38',
 '_39',
 '_4',
 '_40',
 '_41',
 '_42',
 '_43',
 '_44',
 '_45',
 '_46',
 '_47',
 '_48',
 '_49',
 '_50',
 '_51',
 '_52',
 '_53',
 '_54',
 '_55',
 '_56',
 '_57',
 '_58',
 '_59',
 '_6',
 '_60',
 '_61',
 '_62',
 '_63',
 '_65',
 '_66',
 '_68',
 '_69',
 '_70',
 '_71',
 '_73',
 '_74',
 '_75',
 '_76',
 '_77',
 '_78',
 '_79',
 '_80',
 '_81',
 '_82',
 '_83',
 '_86',
 '_87',
 '_88',
 '_89',
 '_90',
 '_91',
 '_92',
 '_93',
 '_94',
 '_95',
 '_97',
 '_99',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i100',
 '_i101',
 '_i102',
 '_i103',
 '_i104',
 '_i105',
 '_i106',
 '_i107',
 '_i108',
 '_i109',
 '_i11',
 '_i110',
 '_i111',
 '_i112',
 '_i113',
 '_i12',
 '_i13',
 '_i14',


In [143]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [116]:
import matplotlib.pyplot as plt  
dir(plt.hist)

['__annotations__',
 '__builtins__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [139]:
"""
help
help(): 도움말 기능, 함수와 함수에 속한 각 옵션에 대한 설명을 볼 수 있다.
"""
help()


Welcome to Python 3.10's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the internet at https://docs.python.org/3.10/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".


You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [121]:
help(plt.plot)

Help on function plot in module matplotlib.pyplot:

plot(*args, scalex=True, scaley=True, data=None, **kwargs)
    Plot y versus x as lines and/or markers.
    
    Call signatures::
    
        plot([x], y, [fmt], *, data=None, **kwargs)
        plot([x], y, [fmt], [x2], y2, [fmt2], ..., **kwargs)
    
    The coordinates of the points or line nodes are given by *x*, *y*.
    
    The optional parameter *fmt* is a convenient way for defining basic
    formatting like color, marker and linestyle. It's a shortcut string
    notation described in the *Notes* section below.
    
    >>> plot(x, y)        # plot x and y using default line style and color
    >>> plot(x, y, 'bo')  # plot x and y using blue circle markers
    >>> plot(y)           # plot y using x as index array 0..N-1
    >>> plot(y, 'r+')     # ditto, but with red plusses
    
    You can use `.Line2D` properties as keyword arguments for more
    control on the appearance. Line properties and *fmt* can be mixed.
    The f

In [122]:
# help(dataframe.corr)

## 패키지 사용

패키지를 사용하기 위해서는 import 명령어를 사용한다.

In [139]:
import numpy as np

예약어(약자)를 사용하여 패키지를 불러온 후 그 기능을 사용하는 경우에는 약자를 접두어로 붙여 사용한다. 다음의 간단한 예를 확인해보자. 

In [140]:
import numpy as np
a=[1,2,3,4,5]
np.sum(a)

15

numpy 패키지를 약자 np를 사용하여 import 하였다. 그리고 리스트로 작성된 변수 a에 대하여 numpy에 포함된 기본 통계 함수(메소드)인 sum을 사용하여 변수의 합을 구할 수 있다. 

- hist() 함수를 사용할 수 있는 다양한 방법

In [141]:
import matplotlib                      #  matplotlib.pyplot.hist(변수)
import matplotlib as plt               #  plt.pyplot.hist(변수)
import matplotlib.pyplot as plt        #  plt.hist(변수)
from matplotlib.pyplot import hist     #  hist(변수)